In [55]:
using DataFrames
df = readtable("houses.csv")
df = df[df[:sq__ft].>0,:]
X = df[[:beds,:baths,:sq__ft]]
y = df[:price]
m = length(y)
@show [X y]

[X y] = 814×4 DataFrames.DataFrame
│ Row │ beds │ baths │ sq__ft │ x1     │
├─────┼──────┼───────┼────────┼────────┤
│ 1   │ 2    │ 1     │ 836    │ 59222  │
│ 2   │ 3    │ 1     │ 1167   │ 68212  │
│ 3   │ 2    │ 1     │ 796    │ 68880  │
│ 4   │ 2    │ 1     │ 852    │ 69307  │
│ 5   │ 2    │ 1     │ 797    │ 81900  │
│ 6   │ 3    │ 1     │ 1122   │ 89921  │
│ 7   │ 3    │ 2     │ 1104   │ 90895  │
│ 8   │ 3    │ 1     │ 1177   │ 91002  │
│ 9   │ 2    │ 2     │ 941    │ 94905  │
│ 10  │ 3    │ 2     │ 1146   │ 98937  │
│ 11  │ 3    │ 2     │ 909    │ 100309 │
│ 12  │ 3    │ 2     │ 1289   │ 106250 │
│ 13  │ 1    │ 1     │ 871    │ 106852 │
│ 14  │ 3    │ 1     │ 1020   │ 107502 │
│ 15  │ 2    │ 2     │ 1022   │ 108750 │
│ 16  │ 2    │ 2     │ 1134   │ 110700 │
│ 17  │ 2    │ 1     │ 844    │ 113263 │
│ 18  │ 2    │ 1     │ 795    │ 116250 │
│ 19  │ 2    │ 1     │ 588    │ 120000 │
│ 20  │ 3    │ 2     │ 1356   │ 121630 │
│ 21  │ 3    │ 2     │ 1118   │ 122000 │
│ 22  │ 4    │ 2     │

814×4 DataFrames.DataFrame
│ Row │ beds │ baths │ sq__ft │ x1     │
├─────┼──────┼───────┼────────┼────────┤
│ 1   │ 2    │ 1     │ 836    │ 59222  │
│ 2   │ 3    │ 1     │ 1167   │ 68212  │
│ 3   │ 2    │ 1     │ 796    │ 68880  │
│ 4   │ 2    │ 1     │ 852    │ 69307  │
│ 5   │ 2    │ 1     │ 797    │ 81900  │
│ 6   │ 3    │ 1     │ 1122   │ 89921  │
│ 7   │ 3    │ 2     │ 1104   │ 90895  │
│ 8   │ 3    │ 1     │ 1177   │ 91002  │
│ 9   │ 2    │ 2     │ 941    │ 94905  │
│ 10  │ 3    │ 2     │ 1146   │ 98937  │
│ 11  │ 3    │ 2     │ 909    │ 100309 │
⋮
│ 803 │ 3    │ 1     │ 960    │ 224252 │
│ 804 │ 3    │ 1     │ 1456   │ 225000 │
│ 805 │ 3    │ 2     │ 1450   │ 228000 │
│ 806 │ 3    │ 2     │ 1358   │ 229027 │
│ 807 │ 4    │ 2     │ 1329   │ 229500 │
│ 808 │ 4    │ 2     │ 1715   │ 230000 │
│ 809 │ 3    │ 2     │ 1262   │ 230000 │
│ 810 │ 4    │ 3     │ 2280   │ 232425 │
│ 811 │ 3    │ 2     │ 1477   │ 234000 │
│ 812 │ 3    │ 2     │ 1216   │ 235000 │
│ 813 │ 4    │ 2     │ 1685   │ 235301 │
│ 814 │ 3    │ 2     │ 1362   │ 235738 │

In [56]:
mu_vals = zeros(size(X,2))
std_vals = zeros(size(X,2))
for i = 1:size(X,2)
    mu_vals[i] = mean(X[:,i])
    std_vals[i] = std(X[:,i])
    X[:,i] = (X[:,i] - mu_vals[i])/std_vals[i]
end

In [57]:
intercept = DataFrame(intercept=ones(Int64,m))
P = [intercept  X]

814×4 DataFrames.DataFrame
│ Row │ intercept │ beds      │ baths     │ sq__ft    │
├─────┼───────────┼───────────┼───────────┼───────────┤
│ 1   │ 1         │ -1.46041  │ -1.43428  │ -1.13754  │
│ 2   │ 1         │ -0.286892 │ -1.43428  │ -0.638926 │
│ 3   │ 1         │ -1.46041  │ -1.43428  │ -1.19779  │
│ 4   │ 1         │ -1.46041  │ -1.43428  │ -1.11344  │
│ 5   │ 1         │ -1.46041  │ -1.43428  │ -1.19629  │
│ 6   │ 1         │ -0.286892 │ -1.43428  │ -0.706714 │
│ 7   │ 1         │ -0.286892 │ 0.0586919 │ -0.733829 │
│ 8   │ 1         │ -0.286892 │ -1.43428  │ -0.623863 │
│ 9   │ 1         │ -1.46041  │ 0.0586919 │ -0.979369 │
│ 10  │ 1         │ -0.286892 │ 0.0586919 │ -0.670561 │
│ 11  │ 1         │ -0.286892 │ 0.0586919 │ -1.02757  │
⋮
│ 803 │ 1         │ -0.286892 │ -1.43428  │ -0.950748 │
│ 804 │ 1         │ -0.286892 │ -1.43428  │ -0.203582 │
│ 805 │ 1         │ -0.286892 │ 0.0586919 │ -0.21262  │
│ 806 │ 1         │ -0.286892 │ 0.0586919 │ -0.351207 │
│ 807 │ 1         │ 0.886627  │ 0.0586919 │ -0.394892 │
│ 808 │ 1         │ 0.886627  │ 0.0586919 │ 0.186571  │
│ 809 │ 1         │ -0.286892 │ 0.0586919 │ -0.49582  │
│ 810 │ 1         │ 0.886627  │ 1.55167   │ 1.03768   │
│ 811 │ 1         │ -0.286892 │ 0.0586919 │ -0.171948 │
│ 812 │ 1         │ -0.286892 │ 0.0586919 │ -0.565114 │
│ 813 │ 1         │ 0.886627  │ 0.0586919 │ 0.14138   │
│ 814 │ 1         │ -0.286892 │ 0.0586919 │ -0.345182 │

In [58]:
α = 0.015
num_iters = 100
n = size(P,2)
θ = zeros(n)
history = zeros(num_iters, 1)

100x1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [59]:
X = Array(P)

814x4 Array{Real,2}:
 1  -1.46041   -1.43428    -1.13754 
 1  -0.286892  -1.43428    -0.638926
 1  -1.46041   -1.43428    -1.19779 
 1  -1.46041   -1.43428    -1.11344 
 1  -1.46041   -1.43428    -1.19629 
 1  -0.286892  -1.43428    -0.706714
 1  -0.286892   0.0586919  -0.733829
 1  -0.286892  -1.43428    -0.623863
 1  -1.46041    0.0586919  -0.979369
 1  -0.286892   0.0586919  -0.670561
 1  -0.286892   0.0586919  -1.02757 
 1  -0.286892   0.0586919  -0.455148
 1  -2.63393   -1.43428    -1.08482 
 ⋮                                  
 1  -0.286892  -1.43428    -0.950748
 1  -0.286892  -1.43428    -0.203582
 1  -0.286892   0.0586919  -0.21262 
 1  -0.286892   0.0586919  -0.351207
 1   0.886627   0.0586919  -0.394892
 1   0.886627   0.0586919   0.186571
 1  -0.286892   0.0586919  -0.49582 
 1   0.886627   1.55167     1.03768 
 1  -0.286892   0.0586919  -0.171948
 1  -0.286892   0.0586919  -0.565114
 1   0.886627   0.0586919   0.14138 
 1  -0.286892   0.0586919  -0.345182

In [60]:
for iter = 1:num_iters
    δ = 1/m*(X'*X*θ-X'*y)
    θ = θ - α.*δ
    v = X*θ
    j = 1/(2*m)*sum((v-y).^2)
    history[iter] = j
end

In [61]:
history

100x1 Array{Float64,2}:
 3.25138e10
 3.15707e10
 3.06626e10
 2.97881e10
 2.89457e10
 2.81339e10
 2.73515e10
 2.65972e10
 2.58698e10
 2.51682e10
 2.44914e10
 2.38383e10
 2.32079e10
 ⋮         
 5.85374e9 
 5.79721e9 
 5.74231e9 
 5.68899e9 
 5.63721e9 
 5.58691e9 
 5.53805e9 
 5.4906e9  
 5.4445e9  
 5.39972e9 
 5.35623e9 
 5.31397e9 

In [62]:
d = [1.0,2,1,836]
d[2:end] =  d[2:end] - mu_vals 
d[2:end] = d[2:end]./std_vals
price = dot(d,θ)

78190.29894124044

In [46]:
θ

4-element DataArrays.DataArray{Real,1}:
 199019.0 
   9663.68
  18428.0 
  53062.6 